---
- name: 'Run a simple privileged (rootful) nginx container with Podman'
  hosts: 'all'
  gather_facts: true

  roles:
    - role: 'johanneskastl.podman_nginx'
      podman_nginx_rootful_container: true
