---

- name: 'Run 10_SLES_register.yml'
  ansible.builtin.import_playbook: 10_SLES_register.yml

- name: 'Run playbook-all_nodes-zypper_ref_accept_keys.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-zypper_ref_accept_keys.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-install_podman.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_podman.yml

#
# rootless container
#
- name: 'Run playbook-all_nodes-podman_nginx.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-podman_nginx.yml

- name: 'Run playbook-all_nodes-create_index.html'
  ansible.builtin.import_playbook: playbook-all_nodes-create_index.html
